//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsCRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int OrderId { get; set; }
        public string Domain { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderStatus { get; set; }
        public int MarketingWay { get; set; }
        public decimal Total { get; set; }
        public string Description { get; set; }
        public Nullable<int> Product_ProductId { get; set; }
        public string User_UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
